"""Initial migration

Revision ID: 6590987bdf83
Revises: 
Create Date: 2025-09-04 21:15:43.641182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6590987bdf83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('level_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('level_code')
    )
    op.create_table('main_topics',
    sa.Column('main_topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('main_topic_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sub_topics',
    sa.Column('sub_topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['main_topic_id'], ['main_topics.main_topic_id'], ),
    sa.PrimaryKeyConstraint('sub_topic_id')
    )
    op.create_table('learning_paths',
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('sub_topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sub_topic_id'], ['sub_topics.sub_topic_id'], ),
    sa.PrimaryKeyConstraint('path_id')
    )
    op.create_table('curriculum_items',
    sa.Column('curriculum_item_id', sa.String(), nullable=False),
    sa.Column('sub_topic_id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.path_id'], ),
    sa.ForeignKeyConstraint(['sub_topic_id'], ['sub_topics.sub_topic_id'], ),
    sa.PrimaryKeyConstraint('curriculum_item_id')
    )
    op.create_index('idx_path_sort_order', 'curriculum_items', ['path_id', 'sort_order'], unique=True)
    op.create_index('idx_sub_topic_id', 'curriculum_items', ['sub_topic_id'], unique=False)
    op.create_table('articles',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('curriculum_item_id', sa.String(), nullable=False),
    sa.Column('sub_topic_id', sa.Integer(), nullable=False),
    sa.Column('level_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_item_id'], ['curriculum_items.curriculum_item_id'], ),
    sa.ForeignKeyConstraint(['level_code'], ['levels.level_code'], ),
    sa.ForeignKeyConstraint(['sub_topic_id'], ['sub_topics.sub_topic_id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index('idx_curriculum_item_level', 'articles', ['curriculum_item_id', 'level_code'], unique=True)
    op.create_index('idx_sub_topic_level', 'articles', ['sub_topic_id', 'level_code'], unique=False)
    op.create_table('user_article_reads',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'article_id')
    )
    op.create_index('idx_user_read_at', 'user_article_reads', ['user_id', 'read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_read_at', table_name='user_article_reads')
    op.drop_table('user_article_reads')
    op.drop_index('idx_sub_topic_level', table_name='articles')
    op.drop_index('idx_curriculum_item_level', table_name='articles')
    op.drop_table('articles')
    op.drop_index('idx_sub_topic_id', table_name='curriculum_items')
    op.drop_index('idx_path_sort_order', table_name='curriculum_items')
    op.drop_table('curriculum_items')
    op.drop_table('learning_paths')
    op.drop_table('sub_topics')
    op.drop_table('users')
    op.drop_table('main_topics')
    op.drop_table('levels')
    # ### end Alembic commands ###
