"""add generated sub topics tables

Revision ID: 708181702690
Revises: a7dc518e09ea
Create Date: 2025-09-01 00:03:26.923291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708181702690'
down_revision: Union[str, Sequence[str], None] = 'a7dc518e09ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtopic_generation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('main_topic_id', sa.Integer(), nullable=False),
    sa.Column('personalization_data', sa.JSON(), nullable=True),
    sa.Column('generation_parameters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('total_generated', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['main_topic_id'], ['main_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtopic_generation_requests_id'), 'subtopic_generation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_subtopic_generation_requests_main_topic_id'), 'subtopic_generation_requests', ['main_topic_id'], unique=False)
    op.create_index(op.f('ix_subtopic_generation_requests_user_id'), 'subtopic_generation_requests', ['user_id'], unique=False)
    op.create_table('generated_sub_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_topic_id', sa.Integer(), nullable=False),
    sa.Column('generation_request_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty_score', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generation_request_id'], ['subtopic_generation_requests.id'], ),
    sa.ForeignKeyConstraint(['main_topic_id'], ['main_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_sub_topics_generation_request_id'), 'generated_sub_topics', ['generation_request_id'], unique=False)
    op.create_index(op.f('ix_generated_sub_topics_id'), 'generated_sub_topics', ['id'], unique=False)
    op.create_index(op.f('ix_generated_sub_topics_main_topic_id'), 'generated_sub_topics', ['main_topic_id'], unique=False)
    op.create_index(op.f('ix_generated_sub_topics_title'), 'generated_sub_topics', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_sub_topics_title'), table_name='generated_sub_topics')
    op.drop_index(op.f('ix_generated_sub_topics_main_topic_id'), table_name='generated_sub_topics')
    op.drop_index(op.f('ix_generated_sub_topics_id'), table_name='generated_sub_topics')
    op.drop_index(op.f('ix_generated_sub_topics_generation_request_id'), table_name='generated_sub_topics')
    op.drop_table('generated_sub_topics')
    op.drop_index(op.f('ix_subtopic_generation_requests_user_id'), table_name='subtopic_generation_requests')
    op.drop_index(op.f('ix_subtopic_generation_requests_main_topic_id'), table_name='subtopic_generation_requests')
    op.drop_index(op.f('ix_subtopic_generation_requests_id'), table_name='subtopic_generation_requests')
    op.drop_table('subtopic_generation_requests')
    # ### end Alembic commands ###
