"""Initial migration: Add Level, MainTopic, CuratedSubTopic models

Revision ID: f34b344200d4
Revises: 
Create Date: 2025-08-30 21:47:06.597788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34b344200d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.String(length=200), nullable=False),
    sa.Column('characteristics', sa.JSON(), nullable=False),
    sa.Column('estimated_hours_per_week', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_code'), 'levels', ['code'], unique=True)
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.create_index(op.f('ix_levels_order'), 'levels', ['order'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('main_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main_topics_id'), 'main_topics', ['id'], unique=False)
    op.create_index(op.f('ix_main_topics_level_id'), 'main_topics', ['level_id'], unique=False)
    op.create_index(op.f('ix_main_topics_title'), 'main_topics', ['title'], unique=False)
    op.create_table('curated_sub_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_topic_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty_score', sa.Integer(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['main_topic_id'], ['main_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curated_sub_topics_id'), 'curated_sub_topics', ['id'], unique=False)
    op.create_index(op.f('ix_curated_sub_topics_level_id'), 'curated_sub_topics', ['level_id'], unique=False)
    op.create_index(op.f('ix_curated_sub_topics_main_topic_id'), 'curated_sub_topics', ['main_topic_id'], unique=False)
    op.create_index(op.f('ix_curated_sub_topics_title'), 'curated_sub_topics', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curated_sub_topics_title'), table_name='curated_sub_topics')
    op.drop_index(op.f('ix_curated_sub_topics_main_topic_id'), table_name='curated_sub_topics')
    op.drop_index(op.f('ix_curated_sub_topics_level_id'), table_name='curated_sub_topics')
    op.drop_index(op.f('ix_curated_sub_topics_id'), table_name='curated_sub_topics')
    op.drop_table('curated_sub_topics')
    op.drop_index(op.f('ix_main_topics_title'), table_name='main_topics')
    op.drop_index(op.f('ix_main_topics_level_id'), table_name='main_topics')
    op.drop_index(op.f('ix_main_topics_id'), table_name='main_topics')
    op.drop_table('main_topics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_levels_order'), table_name='levels')
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_index(op.f('ix_levels_code'), table_name='levels')
    op.drop_table('levels')
    # ### end Alembic commands ###
